### ISSUE TITLE
Pouvoir exclure les donnés aberrantes des graphiques

### ISSUE THREAD

**Issue by TheoLechemia** [PnEcrins/istSOS-viewer#3]
Les données aberrantes entraînent un aplatissement des graphes. Il serait bien de pouvoir les exclure

**Comment by camillemonchicourt** [comment]
C'est pas plutôt un travail en amont côté istSOS de leur attribuer un code de qualité indiquant qu'elles ne sont pas bonnes, au regard des regles de qualité, et dans ce cas, elles ne remontent déjà pas, non ?

**Comment by TheoLechemia** [comment]
si, l'idée est de se baser sur les data QA.
Mais l'API remonte tout elle

**Comment by camillemonchicourt** [comment]
OK OK.
Bon c'est dommage de filtrer les données au niveau du viewer, mais si pas le choix.

**Comment by TheoLechemia** [comment]
Fait via une selection d'une plage de valeur à exclure dans l'interface : 
![Capture d’écran du 2024-05-17 11-42-25](https://github.com/PnEcrins/istSOS-viewer/assets/15265745/9936ad61-e0c0-4c43-b828-0593b8158a38)
